# Generated by Django 5.1 on 2024-08-28 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_photo_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 28, 18, 25, 16, 450017)),
        ),
    ]
