# Generated by Django 5.1 on 2024-09-19 17:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_photo_image_alter_photo_publish_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 14, 15, 4, 338281)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='tag',
            field=models.CharField(choices=[('NEBULOSA', 'nebulosa'), ('ESTRELA', 'estrela'), ('GÁLAXIA', 'galaxia'), ('PLANETA', 'planeta'), ('Satélites', 'satelites')], default='', max_length=100),
        ),
    ]
