# Generated by Django 5.1 on 2024-10-17 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_photo_user_alter_photo_publish_date_alter_photo_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 17, 15, 35, 46, 603434)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
