# Generated by Django 5.1 on 2024-10-18 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0008_alter_photo_publish_date_alter_photo_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 18, 16, 35, 1, 447340)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='tag',
            field=models.CharField(choices=[('NEBULOSA', 'nebulosa'), ('ESTRELA', 'estrela'), ('GALÁXIA', 'galaxia'), ('PLANETA', 'planeta'), ('SATÉLITES', 'satelites')], default='', max_length=100),
        ),
    ]
