# Generated by Django 5.1 on 2024-08-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tag',
            field=models.CharField(choices=[('NEBULOSA', 'nebulosa'), ('ESTRELA', 'estrela'), ('GÁLAXIA', 'galaxia'), ('PLANETA', 'planeta'), ('CORPOS CELESTES', 'corpos celestes')], default='', max_length=100),
        ),
    ]
